version: '3.8'

services:
  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - todo-network
    env_file:
      - .env

networks:
  todo-network:
    driver: bridge
