# Generated by Django 5.1.3 on 2024-12-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='todoitems',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
