# Generated by Django 5.1.3 on 2024-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_todoitems_tags_delete_tag_todoitems_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoitems',
            name='tags',
        ),
        migrations.AddField(
            model_name='todoitems',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Item_Tags', to='App.tags'),
        ),
    ]
