# Generated by Django 5.1.3 on 2024-12-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_tags_remove_todoitems_tags_todoitems_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='todoitems',
            name='tags',
            field=models.ManyToManyField(blank=True, to='App.tags'),
        ),
    ]
