# Generated by Django 5.1.3 on 2024-12-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_tags_options_alter_todoitems_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={},
        ),
    ]
